<?xml version="1.0" encoding="UTF-8"?>
<ticket>
  <assigned-user-id type="integer" nil="true"></assigned-user-id>
  <attachments-count type="integer">0</attachments-count>
  <closed type="boolean">true</closed>
  <created-at type="datetime">2009-01-17T18:22:42+00:00</created-at>
  <creator-id type="integer">4023</creator-id>
  <milestone-due-on type="datetime" nil="true"></milestone-due-on>
  <milestone-id type="integer">9903</milestone-id>
  <number type="integer">1776</number>
  <permalink>models-named-test-cause-test-failures</permalink>
  <priority type="integer">1080</priority>
  <project-id type="integer">8994</project-id>
  <raw-data type="binary" nil="true" encoding="base64"></raw-data>
  <state>wontfix</state>
  <tag>tests</tag>
  <title>Models Named Test* cause test failures</title>
  <updated-at type="datetime">2009-01-17T23:31:50+00:00</updated-at>
  <user-id type="integer">141</user-id>
  <version type="integer">3</version>
  <user-name>Michael Koziarski</user-name>
  <creator-name>Chris</creator-name>
  <url>http://rails.lighthouseapp.com/projects/8994/tickets/1776</url>
  <milestone-title>2.x</milestone-title>
  <priority-name nil="true"></priority-name>
  <original-body>We do A/B tests and multivariate testing in my rails app and so we have some models named Test*

This is causing some unfortunate testing errors:

  $ rails -v
  Rails 2.1.1

  $ rails foo
  $ cd foo
  $ ./script/generate model test_something
  $ rake db:migrate
  $ rake test

    1) Error:
  test_somethings(ActionController::TestCase):
  ArgumentError: wrong number of arguments (0 for 1)
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `initialize'
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `new'
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `setup_controller_request_and_response'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `send'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `evaluate_method'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:161:in `call'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `each'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `send'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:272:in `run_callbacks'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/testing/setup_and_teardown.rb:65:in `run'

  6 tests, 1 assertions, 0 failures, 1 errors</original-body>
  <latest-body>We do A/B tests and multivariate testing in my rails app and so we have some models named Test*

This is causing some unfortunate testing errors:

  $ rails -v
  Rails 2.1.1

  $ rails foo
  $ cd foo
  $ ./script/generate model test_something
  $ rake db:migrate
  $ rake test

    1) Error:
  test_somethings(ActionController::TestCase):
  ArgumentError: wrong number of arguments (0 for 1)
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `initialize'
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `new'
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `setup_controller_request_and_response'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `send'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `evaluate_method'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:161:in `call'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `each'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `send'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:272:in `run_callbacks'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/testing/setup_and_teardown.rb:65:in `run'

  6 tests, 1 assertions, 0 failures, 1 errors</latest-body>
  <original-body-html>&lt;div&gt;&lt;p&gt;We do A/B tests and multivariate testing in my rails app and so
we have some models named Test*&lt;/p&gt;
&lt;p&gt;This is causing some unfortunate testing errors:&lt;/p&gt;
&lt;p&gt;$ rails -v Rails 2.1.1&lt;/p&gt;
&lt;p&gt;$ rails foo $ cd foo $ ./script/generate model test_something $
rake db:migrate $ rake test&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;1) Error:
&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;test_somethings(ActionController::TestCase): ArgumentError:
wrong number of arguments (0 for 1)&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;  /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `initialize'
  /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `new'
  /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `setup_controller_request_and_response'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `send'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `evaluate_method'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:161:in `call'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `each'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `send'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:272:in `run_callbacks'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/testing/setup_and_teardown.rb:65:in `run'
&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;6 tests, 1 assertions, 0 failures, 1 errors&lt;/p&gt;&lt;/div&gt;</original-body-html>
  <versions type="array">
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>We do A/B tests and multivariate testing in my rails app and so we have some models named Test*

This is causing some unfortunate testing errors:

  $ rails -v
  Rails 2.1.1

  $ rails foo
  $ cd foo
  $ ./script/generate model test_something
  $ rake db:migrate
  $ rake test

    1) Error:
  test_somethings(ActionController::TestCase):
  ArgumentError: wrong number of arguments (0 for 1)
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `initialize'
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `new'
      /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `setup_controller_request_and_response'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `send'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `evaluate_method'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:161:in `call'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `each'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `send'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:272:in `run_callbacks'
      /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/testing/setup_and_teardown.rb:65:in `run'

  6 tests, 1 assertions, 0 failures, 1 errors</body>
      <body-html>&lt;div&gt;&lt;p&gt;We do A/B tests and multivariate testing in my rails app and so
we have some models named Test*&lt;/p&gt;
&lt;p&gt;This is causing some unfortunate testing errors:&lt;/p&gt;
&lt;p&gt;$ rails -v Rails 2.1.1&lt;/p&gt;
&lt;p&gt;$ rails foo $ cd foo $ ./script/generate model test_something $
rake db:migrate $ rake test&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;1) Error:
&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;test_somethings(ActionController::TestCase): ArgumentError:
wrong number of arguments (0 for 1)&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;  /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `initialize'
  /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `new'
  /Library/Ruby/Gems/1.8/gems/actionpack-2.1.1/lib/action_controller/test_case.rb:73:in `setup_controller_request_and_response'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `send'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:173:in `evaluate_method'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:161:in `call'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `each'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `send'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:90:in `run'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/callbacks.rb:272:in `run_callbacks'
  /Library/Ruby/Gems/1.8/gems/activesupport-2.1.1/lib/active_support/testing/setup_and_teardown.rb:65:in `run'
&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;6 tests, 1 assertions, 0 failures, 1 errors&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2009-01-17T18:22:42+00:00</created-at>
      <creator-id type="integer">4023</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1776</number>
      <permalink>models-named-test-cause-test-failures</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag>tests</tag>
      <title>Models Named Test* cause test failures</title>
      <updated-at type="datetime">2009-01-17T18:22:46+00:00</updated-at>
      <user-id type="integer">4023</user-id>
      <version type="integer">1</version>
      <user-name>Chris</user-name>
      <creator-name>Chris</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1776</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>This is a gotcha with the fixture loading; if you remove test_somethings.yml from fixtures/ the test will pass.

The conflict comes from the accessor method that AR generates; it would be test_somethings(:fixture_name) for this case. Unfortunately, then Test::Unit tries to run that function...</body>
      <body-html>&lt;div&gt;&lt;p&gt;This is a gotcha with the fixture loading; if you remove
test_somethings.yml from fixtures/ the test will pass.&lt;/p&gt;
&lt;p&gt;The conflict comes from the accessor method that AR generates;
it would be test_somethings(:fixture_name) for this case.
Unfortunately, then Test::Unit tries to run that function...&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2009-01-17T21:01:58+00:00</created-at>
      <creator-id type="integer">4023</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1776</number>
      <permalink>models-named-test-cause-test-failures</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag>tests</tag>
      <title>Models Named Test* cause test failures</title>
      <updated-at type="datetime">2009-01-17T21:02:03+00:00</updated-at>
      <user-id type="integer">22589</user-id>
      <version type="integer">2</version>
      <user-name>Matt Jones</user-name>
      <creator-name>Chris</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1776</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>This is an inherent limitation with test/unit.  The fixture accessors are treated as test methods.

The only option short of renaming all those models is to not use the fixtures as mentioned by matt.</body>
      <body-html>&lt;div&gt;&lt;p&gt;This is an inherent limitation with test/unit. The fixture
accessors are treated as test methods.&lt;/p&gt;
&lt;p&gt;The only option short of renaming all those models is to not use
the fixtures as mentioned by matt.&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-01-17T23:31:45+00:00</created-at>
      <creator-id type="integer">4023</creator-id>
      <diffable-attributes type="yaml">--- 
:state: new
</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1776</number>
      <permalink>models-named-test-cause-test-failures</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>wontfix</state>
      <tag>tests</tag>
      <title>Models Named Test* cause test failures</title>
      <updated-at type="datetime">2009-01-17T23:31:50+00:00</updated-at>
      <user-id type="integer">141</user-id>
      <version type="integer">3</version>
      <user-name>Michael Koziarski</user-name>
      <creator-name>Chris</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1776</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
  </versions>
</ticket>
