<?xml version="1.0" encoding="UTF-8"?>
<ticket>
  <assigned-user-id type="integer" nil="true"></assigned-user-id>
  <attachments-count type="integer">0</attachments-count>
  <closed type="boolean">true</closed>
  <created-at type="datetime">2010-07-23T16:51:42+01:00</created-at>
  <creator-id type="integer">108551</creator-id>
  <milestone-due-on type="datetime" nil="true"></milestone-due-on>
  <milestone-id type="integer" nil="true"></milestone-id>
  <number type="integer">5187</number>
  <permalink>fail-rollback-transaction-with-manual-raise-exception</permalink>
  <priority type="integer">3</priority>
  <project-id type="integer">8994</project-id>
  <raw-data type="binary" nil="true" encoding="base64"></raw-data>
  <state>invalid</state>
  <tag>activecord &quot;rails 2.3.4&quot;</tag>
  <title>fail rollback transaction with manual raise exception</title>
  <updated-at type="datetime">2010-07-26T20:24:37+01:00</updated-at>
  <user-id type="integer">40263</user-id>
  <version type="integer">4</version>
  <user-name>Neeraj Singh</user-name>
  <creator-name>Carlos Forero</creator-name>
  <url>http://rails.lighthouseapp.com/projects/8994/tickets/5187</url>
  <priority-name>Low</priority-name>
  <original-body>With :
 PostgreSQL 8.4 or postgresql-8.3
 rails 2.3.4
 pg 9.x or pg 8.x

I test this code:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise ActiveRecord::Rollback.new
     end
   end
end
@@@

and this:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise Exception.new
     end
  end
end
@@@ 

and this:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def self.create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise &quot;Please, rollback&quot;
     end
   end
end
@@@ 

but the record bank is saved succesfully into database

(I reported the problem in the community of pg driver, but they
demonstrated that the problem is not the pg driver
http://bitbucket.org/ged/ruby-pg/issue/37/fail-rollback-transaction-with-manual-raise)</original-body>
  <latest-body>With :
 PostgreSQL 8.4 or postgresql-8.3
 rails 2.3.4
 pg 9.x or pg 8.x

I test this code:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise ActiveRecord::Rollback.new
     end
   end
end
@@@

and this:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise Exception.new
     end
  end
end
@@@ 

and this:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def self.create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise &quot;Please, rollback&quot;
     end
   end
end
@@@ 

but the record bank is saved succesfully into database

(I reported the problem in the community of pg driver, but they
demonstrated that the problem is not the pg driver
http://bitbucket.org/ged/ruby-pg/issue/37/fail-rollback-transaction-with-manual-raise)</latest-body>
  <original-body-html>&lt;div&gt;&lt;p&gt;With :&lt;br&gt;
PostgreSQL 8.4 or postgresql-8.3 rails 2.3.4 pg 9.x or pg 8.x&lt;/p&gt;
&lt;p&gt;I test this code:&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;class NkiBatch &amp;lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&amp;gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise ActiveRecord::Rollback.new
     end
   end
end&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;and this:&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;class NkiBatch &amp;lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&amp;gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise Exception.new
     end
  end
end&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;and this:&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;class NkiBatch &amp;lt; ActiveRecord::Base
   def self.create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&amp;gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise &quot;Please, rollback&quot;
     end
   end
end&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;but the record bank is saved succesfully into database&lt;/p&gt;
&lt;p&gt;(I reported the problem in the community of pg driver, but they
demonstrated that the problem is not the pg driver&lt;br&gt;
&lt;a href=
&quot;http://bitbucket.org/ged/ruby-pg/issue/37/fail-rollback-transaction-with-manual-raise&quot;&gt;
http://bitbucket.org/ged/ruby-pg/issue/37/fail-rollback-transaction...&lt;/a&gt;)&lt;/p&gt;&lt;/div&gt;</original-body-html>
  <versions type="array">
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>With :
 PostgreSQL 8.4 or postgresql-8.3
 rails 2.3.4
 pg 9.x or pg 8.x

I test this code:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise ActiveRecord::Rollback.new
     end
   end
end
@@@

and this:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise Exception.new
     end
  end
end
@@@ 

and this:

@@@ 
class NkiBatch &lt; ActiveRecord::Base
   def self.create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise &quot;Please, rollback&quot;
     end
   end
end
@@@ 

but the record bank is saved succesfully into database

(I reported the problem in the community of pg driver, but they
demonstrated that the problem is not the pg driver
http://bitbucket.org/ged/ruby-pg/issue/37/fail-rollback-transaction-with-manual-raise)</body>
      <body-html>&lt;div&gt;&lt;p&gt;With :&lt;br&gt;
PostgreSQL 8.4 or postgresql-8.3 rails 2.3.4 pg 9.x or pg 8.x&lt;/p&gt;
&lt;p&gt;I test this code:&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;class NkiBatch &amp;lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&amp;gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise ActiveRecord::Rollback.new
     end
   end
end&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;and this:&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;class NkiBatch &amp;lt; ActiveRecord::Base
   def create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&amp;gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise Exception.new
     end
  end
end&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;and this:&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;class NkiBatch &amp;lt; ActiveRecord::Base
   def self.create_batches
     Bank.connection.transaction do

       bank = Bank.new(:name =&amp;gt; &quot;ddsjdsjdsjk&quot;)
       bank.save!
       raise &quot;Please, rollback&quot;
     end
   end
end&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;but the record bank is saved succesfully into database&lt;/p&gt;
&lt;p&gt;(I reported the problem in the community of pg driver, but they
demonstrated that the problem is not the pg driver&lt;br&gt;
&lt;a href=
&quot;http://bitbucket.org/ged/ruby-pg/issue/37/fail-rollback-transaction-with-manual-raise&quot;&gt;
http://bitbucket.org/ged/ruby-pg/issue/37/fail-rollback-transaction...&lt;/a&gt;)&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2010-07-23T16:51:42+01:00</created-at>
      <creator-id type="integer">108551</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">5187</number>
      <permalink>fail-rollback-transaction-with-manual-raise-exception</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag>activecord &quot;rails 2.3.4&quot;</tag>
      <title>fail rollback transaction with manual raise exception</title>
      <updated-at type="datetime">2010-07-23T22:24:17+01:00</updated-at>
      <user-id type="integer">108551</user-id>
      <version type="integer">1</version>
      <user-name>Carlos Forero</user-name>
      <creator-name>Carlos Forero</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/5187</url>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>Hope this helps http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html</body>
      <body-html>&lt;div&gt;&lt;p&gt;Hope this helps &lt;a href=
&quot;http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html&quot;&gt;
http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassM...&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2010-07-24T12:37:03+01:00</created-at>
      <creator-id type="integer">108551</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">5187</number>
      <permalink>fail-rollback-transaction-with-manual-raise-exception</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag>activecord &quot;rails 2.3.4&quot;</tag>
      <title>fail rollback transaction with manual raise exception</title>
      <updated-at type="datetime">2010-07-24T12:37:05+01:00</updated-at>
      <user-id type="integer">75004</user-id>
      <version type="integer">2</version>
      <user-name>lakshmanan</user-name>
      <creator-name>Carlos Forero</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/5187</url>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>I'm sorry. The problem was the following code that another developer had added:

@@@ ruby
class ApplicationController &lt; ActionController::Base
  prepend_around_filter :action_transaction

  def action_transaction
    ActiveRecord::Base.transaction do
      yield
    end
  end

end
@@@

thanks anyway</body>
      <body-html>&lt;div&gt;&lt;p&gt;I'm sorry. The problem was the following code that another
developer had added:&lt;/p&gt;
&lt;pre&gt;
&lt;code class=
&quot;ruby&quot;&gt;class ApplicationController &amp;lt; ActionController::Base
  prepend_around_filter :action_transaction

  def action_transaction
    ActiveRecord::Base.transaction do
      yield
    end
  end

end&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;thanks anyway&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2010-07-26T20:03:04+01:00</created-at>
      <creator-id type="integer">108551</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">5187</number>
      <permalink>fail-rollback-transaction-with-manual-raise-exception</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag>activecord &quot;rails 2.3.4&quot;</tag>
      <title>fail rollback transaction with manual raise exception</title>
      <updated-at type="datetime">2010-07-26T20:03:08+01:00</updated-at>
      <user-id type="integer">108551</user-id>
      <version type="integer">3</version>
      <user-name>Carlos Forero</user-name>
      <creator-name>Carlos Forero</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/5187</url>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body></body>
      <body-html></body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2010-07-26T20:24:36+01:00</created-at>
      <creator-id type="integer">108551</creator-id>
      <diffable-attributes type="yaml">--- 
:priority: 0
:state: new
</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">5187</number>
      <permalink>fail-rollback-transaction-with-manual-raise-exception</permalink>
      <priority type="integer">3</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>activecord &quot;rails 2.3.4&quot;</tag>
      <title>fail rollback transaction with manual raise exception</title>
      <updated-at type="datetime">2010-07-26T20:24:37+01:00</updated-at>
      <user-id type="integer">40263</user-id>
      <version type="integer">4</version>
      <user-name>Neeraj Singh</user-name>
      <creator-name>Carlos Forero</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/5187</url>
      <priority-name>Low</priority-name>
    </version>
  </versions>
</ticket>
