<?xml version="1.0" encoding="UTF-8"?>
<ticket>
  <assigned-user-id type="integer" nil="true"></assigned-user-id>
  <attachments-count type="integer">0</attachments-count>
  <closed type="boolean">false</closed>
  <created-at type="datetime">2011-04-18T18:41:26+01:00</created-at>
  <creator-id type="integer">95253</creator-id>
  <milestone-due-on type="datetime" nil="true"></milestone-due-on>
  <milestone-id type="integer" nil="true"></milestone-id>
  <number type="integer">6714</number>
  <permalink>active-record-connection-pool-rails-306</permalink>
  <priority type="integer">0</priority>
  <project-id type="integer">8994</project-id>
  <raw-data type="binary" nil="true" encoding="base64"></raw-data>
  <state>new</state>
  <tag nil="true"></tag>
  <title>Active Record connection pool Rails 3.0.6</title>
  <updated-at type="datetime">2011-04-18T19:32:26+01:00</updated-at>
  <user-id type="integer">95253</user-id>
  <version type="integer">2</version>
  <user-name>chaitanyav</user-name>
  <creator-name>chaitanyav</creator-name>
  <url>http://rails.lighthouseapp.com/projects/8994/tickets/6714</url>
  <priority-name nil="true"></priority-name>
  <original-body>The database connection is not released after the background task finishes, I am seeing this issue after the upgrade to Rails 3.0.6 from 3.0.5. Is anyone else facing this issue with Rails 3.0.6?.

@@@
 prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block (2 levels) in checkout': could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it. (ActiveRecord::ConnectionTimeoutError)
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `loop'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `block in checkout'
	from prefix/tools_64/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:186:in `checkout'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:94:in `connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:317:in `retrieve_connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:97:in `retrieve_connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:89:in `connection'
@@@


Environment Ruby 1.9.2-p180 and Rails 3.0.6 on CentOS 4.5 x86_64

Thank you
Chaitanya</original-body>
  <latest-body>The database connection is not released after the background task finishes, I am seeing this issue after the upgrade to Rails 3.0.6 from 3.0.5. Is anyone else facing this issue with Rails 3.0.6?.

@@@
 prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block (2 levels) in checkout': could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it. (ActiveRecord::ConnectionTimeoutError)
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `loop'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `block in checkout'
	from prefix/tools_64/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:186:in `checkout'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:94:in `connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:317:in `retrieve_connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:97:in `retrieve_connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:89:in `connection'
@@@


Environment Ruby 1.9.2-p180 and Rails 3.0.6 on CentOS 4.5 x86_64

Thank you
Chaitanya</latest-body>
  <original-body-html>&lt;div&gt;&lt;p&gt;The database connection is not released after the background
task finishes, I am seeing this issue after the upgrade to Rails
3.0.6 from 3.0.5. Is anyone else facing this issue with Rails
3.0.6?.&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt; prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block (2 levels) in checkout': could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it. (ActiveRecord::ConnectionTimeoutError)
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `loop'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `block in checkout'
    from prefix/tools_64/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:186:in `checkout'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:94:in `connection'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:317:in `retrieve_connection'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:97:in `retrieve_connection'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:89:in `connection'&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;Environment Ruby 1.9.2-p180 and Rails 3.0.6 on CentOS 4.5
x86_64&lt;/p&gt;
&lt;p&gt;Thank you&lt;br&gt;
Chaitanya&lt;/p&gt;&lt;/div&gt;</original-body-html>
  <versions type="array">
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>The database connection is not released after the background task finishes, I am seeing this issue after the upgrade to Rails 3.0.6 from 3.0.5. Is anyone else facing this issue with Rails 3.0.6?.

@@@
 prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block (2 levels) in checkout': could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it. (ActiveRecord::ConnectionTimeoutError)
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `loop'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `block in checkout'
	from prefix/tools_64/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:186:in `checkout'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:94:in `connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:317:in `retrieve_connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:97:in `retrieve_connection'
	from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:89:in `connection'
@@@


Environment Ruby 1.9.2-p180 and Rails 3.0.6 on CentOS 4.5 x86_64

Thank you
Chaitanya</body>
      <body-html>&lt;div&gt;&lt;p&gt;The database connection is not released after the background
task finishes, I am seeing this issue after the upgrade to Rails
3.0.6 from 3.0.5. Is anyone else facing this issue with Rails
3.0.6?.&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt; prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block (2 levels) in checkout': could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it. (ActiveRecord::ConnectionTimeoutError)
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `loop'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:187:in `block in checkout'
    from prefix/tools_64/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:186:in `checkout'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:94:in `connection'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:317:in `retrieve_connection'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:97:in `retrieve_connection'
    from prefix/tools_64/lib/ruby/gems/1.9.1/gems/activerecord-3.0.6/lib/active_record/connection_adapters/abstract/connection_specification.rb:89:in `connection'&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;Environment Ruby 1.9.2-p180 and Rails 3.0.6 on CentOS 4.5
x86_64&lt;/p&gt;
&lt;p&gt;Thank you&lt;br&gt;
Chaitanya&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2011-04-18T18:41:26+01:00</created-at>
      <creator-id type="integer">95253</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">6714</number>
      <permalink>active-record-connection-pool-rails-306</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag nil="true"></tag>
      <title>Active Record connection pool Rails 3.0.6</title>
      <updated-at type="datetime">2011-04-18T18:41:29+01:00</updated-at>
      <user-id type="integer">95253</user-id>
      <version type="integer">1</version>
      <user-name>chaitanyav</user-name>
      <creator-name>chaitanyav</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/6714</url>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>There was a issue filed before #5736, I think the issue is still not resolved,

@@@
Loading development environment (Rails 3.0.6)
&gt;&gt; Thread.list
=&gt; [#&lt;Thread:0x00000000551e28 run&gt;]
&gt;&gt; 5.times do
?&gt;     Thread.new do
?&gt;       ActiveRecord::Base.connection_pool.checkout
&gt;&gt;     end.join
&gt;&gt;   end
=&gt; 5
&gt;&gt; Thread.list
=&gt; [#&lt;Thread:0x00000000551e28 run&gt;]
&gt;&gt; ActiveRecord::Base.connection_pool.checkout
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it.

@@@

I also manually tried
@@@
&gt;&gt; ActiveRecord::Base.connection_pool.clear_stale_cached_connections!
=&gt; []
&gt;&gt; ActiveRecord::Base.connection_pool.checkout
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it.

@@@

Thank you
Chaitanya</body>
      <body-html>&lt;div&gt;&lt;p&gt;There was a issue filed before &lt;a href=
&quot;/projects/8994/tickets/5736&quot; title=&quot;Ticket #5736&quot;&gt;#5736&lt;/a&gt;, I
think the issue is still not resolved,&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;Loading development environment (Rails 3.0.6)
&amp;gt;&amp;gt; Thread.list
=&amp;gt; [#&amp;lt;Thread:0x00000000551e28 run&amp;gt;]
&amp;gt;&amp;gt; 5.times do
?&amp;gt;     Thread.new do
?&amp;gt;       ActiveRecord::Base.connection_pool.checkout
&amp;gt;&amp;gt;     end.join
&amp;gt;&amp;gt;   end
=&amp;gt; 5
&amp;gt;&amp;gt; Thread.list
=&amp;gt; [#&amp;lt;Thread:0x00000000551e28 run&amp;gt;]
&amp;gt;&amp;gt; ActiveRecord::Base.connection_pool.checkout
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it.&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;I also manually tried&lt;br&gt;&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;&amp;gt;&amp;gt; ActiveRecord::Base.connection_pool.clear_stale_cached_connections!
=&amp;gt; []
&amp;gt;&amp;gt; ActiveRecord::Base.connection_pool.checkout
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5 seconds.  The max pool size is currently 5; consider increasing it.&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;Thank you&lt;br&gt;
Chaitanya&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2011-04-18T19:32:24+01:00</created-at>
      <creator-id type="integer">95253</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">6714</number>
      <permalink>active-record-connection-pool-rails-306</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag nil="true"></tag>
      <title>Active Record connection pool Rails 3.0.6</title>
      <updated-at type="datetime">2011-04-18T19:32:26+01:00</updated-at>
      <user-id type="integer">95253</user-id>
      <version type="integer">2</version>
      <user-name>chaitanyav</user-name>
      <creator-name>chaitanyav</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/6714</url>
      <priority-name nil="true"></priority-name>
    </version>
  </versions>
</ticket>
